name: Python Package using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file Environment/DAT540EANN.yml --name base
    - name: Lint with pycodestyle and pydocstyle
      run: |
        $CONDA/bin/pycodestyle .
        $CONDA/bin/pydocstyle .
    
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        C:\Miniconda\condabin\conda.bat env update --file Environment/DAT540EANN.yml --name base
        C:\Miniconda\condabin\conda.bat init powershell
    - name: Lint with pycodestyle and pydocstyle
      run: |
        C:\Miniconda\condabin\conda.bat activate base
        pycodestyle .
        pydocstyle .

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file Environment/DAT540EANN.yml --name base
    - name: Lint with pycodestyle and pydocstyle
      run: |
        $CONDA/bin/pycodestyle .
        $CONDA/bin/pydocstyle .
    